[dependencies]
core = {}
alloc = {}

[dependencies.compiler_builtins]
features = ["mem"]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
stage = 1

[dependencies.std]
git = "https://github.com/japaric/steed"
stage = 2